#!/bin/bash
set -e
echo



if [[ $# -ne 1 ]]; then
    printf "\033[1;31mERROR \033[0mYou must specify a target\n" 1>&2
    exit 1
fi



if [[ $1 == "ssh-authserver" ]]; then

    printf "\033[0;30mgcc -o .build/linux/ssh-authserver/authserver ssh-authserver/authserver.c $(mariadb_config --libs)\n"
    gcc -o .build/linux/ssh-authserver/authserver ssh-authserver/authserver.c $(mariadb_config --libs)

    printf "\033[1;32mSUCCESS \033[0m$1 linux $(arch)\n"

else
    printf "\033[1;31mERROR \033[0mTarget doesn't exist\n" 1>&2
    exit 1
fi